- name: Copy package
  copy:
    src: mita.deb
    dest: /tmp/mita.deb

- name: Install package
  apt:
    deb: /tmp/mita.deb
    state: present
  notify: Restart mita service

- name: Add root to group
  user:
    name: root
    groups: mita
    append: true

- name: Start service
  systemd:
    name: mita
    state: started
    enabled: true

- name: Create config dir
  file:
    path: /etc/mita
    state: directory
    mode: "0755"

- name: Copy config
  template:
    src: mita.json.j2
    dest: /etc/mita/mita.json
  notify: Apply mita config
