ansible_port: 35790

certificates:
 local_dir: "{{ playbook_dir }}/../files/certs"
 domain: "vikavikavika.ru"

fakesite:
 port: 5000

fileserver:
 name: VIKA-WASSUP
 prefix: sub
 port: 7071

trusttunnel:
 port: 8443
 metrics_port: 8400

mita:
 port_range: "10000-10127"
 protocol: UDP

sudoku:
 port: 443
 fallback_port: 5000
 public_key: b7b1e2c511cf6ae1b4ed9d0cf2d71a38494c7d66b508ae27e51c6b7007eae6d2
 transport: tcp
