ansible_port: 2222

fakesite:
  port: 5000

fileserver:
  name: VPN-FileServer
  prefix: sub
  port: 7071

mita:
  port_range: "10000-10127"
  protocol: UDP

sudoku:
  port: 443
  fallback_port: 5000
  public_key: CHANGE_ME
  transport: tcp

mtproxyl:
  port: 7443
  metrics_port: 7400
  fake_tls_domain: aeza.ru
