ansible_port: 2222

certificates:
  local_dir: "{{ playbook_dir }}/../files/certs"
  domain: "vpn.example.com"

fakesite:
  port: 5000

fileserver:
  name: VPN-FileServer
  prefix: sub
  port: 7071

trusttunnel:
  port: 8443
  metrics_port: 8400

mita:
  port_range: "10000-10127"
  protocol: UDP

sudoku:
  port: 443
  fallback_port: 5000
  public_key: CHANGE_ME
  transport: tcp
